Outline text for resolution
popsim-consortium/demes-spec pull request #123
Opened 2022-02-24 16:09 UTC by jeromekelleher

Here's a start on resolution - any thoughts @grahamgower?

2022-02-25 07:45 UTC, grahamgower requested changes
I think we should more explicitly outline the deme resolution order here.

2022-02-25 07:45 UTC, grahamgower commented on docs/specification.md
> +have been resolved. Subsequently,
I think this should say the following things:
* demes are resolved in the order in which they appear in the input
* a deme can only be resolved if its ancestor demes have already been resolved
* the parser MUST raise an error if a deme is encountered that has unresolved ancestors
* this guarantees that for any valid input file, the demes are sorted topologically (ancestors are listed before their descendants)

2022-02-25 07:45 UTC, grahamgower commented on docs/specification.md
> -  for each deme in ``ancestors``.
I guess this is all stated in the MDM section?

2022-02-25 07:45 UTC, grahamgower commented on docs/specification.md
> +     error should be raised.
MUST be raised

2022-05-05 15:58 UTC, jeromekelleher commented on docs/specification.md
> +have been resolved. Subsequently,
done

2022-05-05 16:03 UTC, jeromekelleher commented
Made those changes @grahamgower. I'll follow up with any other changes separately, let's get this much merged.

2022-05-05 16:21 UTC, merged