Add example of resolving sequential pulses.
popsim-consortium/demes-spec pull request #156
Opened 2022-06-29 19:55 UTC by molpopgen

Add detailed description of pulse resolution.
The content comes from posts in #100.

2022-06-30 06:18 UTC, grahamgower requested changes
Just a few minor wording things.

There's also a section in the tutorial that talks about simultaneous pulses (click on the "answer" to the question below example 17). Maybe some cross-linking between the tutorial and the spec is in order here?
https://popsim-consortium.github.io/demes-spec-docs/main/tutorial.html#a-pulse-of-admixture

2022-06-30 06:18 UTC, grahamgower commented on docs/specification.md
> +## Example: sequential application of pulses
This heading seems to be at the wrong level. Take a look at the rendered page and you'll see that the nesting in the contents (top right) is off. The `### migration` and `### schema` subsections below this should be under the MDM section.  Maybe it should be 3 or 4 `#` marks instead?

2022-06-30 06:18 UTC, grahamgower commented on docs/specification.md
> +We need to arrive at the final ancestry proportions for destination deme `C` at this time.
s/at this time/after this time/

2022-06-30 06:18 UTC, grahamgower commented on docs/specification.md
> +The steps are:
There are clearly two ways to do the sequential application of pulses: 1) apply each pulse one at a time, like what we can do in msprime, or 2) calculate the resulting proportions as you've indicated and sample the parental generation once.

The wording here strongly suggests that case (2) is the only option.
How about "To arrive at the final ancestry proportions for deme `C` after this time:" instead?

2022-06-30 06:26 UTC, grahamgower commented on docs/specification.md
> +  We get `[1/3, 1/6, 1/2]` as our ancestry proportions due to pulses.
Hang on, isn't this is the same model as above? How are the ancestry proportions different?

2022-06-30 11:55 UTC, molpopgen commented on docs/specification.md
> +The steps are:
This comment is the heart of the issue: how is it clear if I'm having to  ask/open issue about what you mean by "apply"?  How would I be expected to know what msprime does?

2022-06-30 12:05 UTC, grahamgower commented on docs/specification.md
> +The steps are:
Don't get me wrong here, I agree with you 100% that additional clarification is needed here. But I think the wording should be more agnostic to how one would implement this, and instead frame the explanation in terms of what the realised ancestry proportions must be after the pulse time.

2022-06-30 12:16 UTC, molpopgen commented on docs/specification.md
> +The steps are:
If you think there is more than one way and all of them work for discrete and continuous simulators, then let me know.  I've never looked at the msprime code, and I probably won't.  I only think about doing this stuff forwards in time.  For that case, "applying things one at a time" doesn't mean there is only one implementation unless you specify exactly how to apply it.  Someone could take the first pulse in this example, draw p*N children from the source deme and (1-p)*N from the destination deme.  Then, the remaining pulses do nothing as the code would probably realize there are no further children needed.  The notion that that is a wrong thing to do is in the comments of #100, but I'd have a hard time arguing they misread the spec--they did indeed apply pulses one at a time.

2022-06-30 12:18 UTC, molpopgen commented on docs/specification.md
> +The steps are:
I think part of the issue may be that we are trying to describe this in words rather than with an equation.

2022-06-30 12:34 UTC, grahamgower commented on docs/specification.md
> +The steps are:
In my head, sequential application means: For the first pulse into destination `C`, draw `p*N` individuals from source deme `A` and `(1-p)*N` from destination deme `C`. For the second pulse into dest `C`, draw `q*N` individuals from the source deme `B` and `(1-q)*N` from the destination deme `C`, where the destination deme `C` is currently made up of `p*N` individuals from `A` and `(1-p)*N` individuals from `C`.

For an individual-based simulator it makes sense to code up this procedure to calculate the realised ancestry proportions and just sample those realised proportions directly. For a coalescent simulator, there is no need to do this as one can just "apply" the pulses in reverse order (i.e. backwards time): observe the second pulse event and move lineages with probability `q`, then observe the first pulse event and move lineages with probability `p`.

2022-06-30 12:53 UTC, molpopgen commented on docs/specification.md
> +The steps are:
I think the trick is to write this down for any number of sources :)

2022-06-30 12:57 UTC, grahamgower commented on docs/specification.md
> +The steps are:
Here you go :P
https://github.com/tskit-dev/msprime/blob/4937d882fe6239d4dcdbe3c94916ce47b380c082/msprime/demography.py#L3511-L3537

2022-07-01 15:10 UTC, molpopgen commented
Little delay on this one: the example is bad.  It has `1/3` in the YAML, but the demes-python rejects that (string not a number).  I'll try to come up with an example that actually works.  This specific example gets confounded w/numerical issues due to trying to write `1/3` as a number, which is actually a whole other concern I hadn't thought of.

2022-07-04 06:41 UTC, grahamgower commented on docs/specification.md
> +   `x[B] += 0.2, x = [0.2, 0.2, 0.6]`
Thanks for the updates @molpopgen.
The formatting just here makes the rendered result hard to read. Maybe a code block would be clearer? (e.g. allowing newlines)

2022-07-04 17:54 UTC, grahamgower approved these changes
Great, thanks @molpopgen! Feel free to squash and merge.

2022-07-04 18:14 UTC, merged