Explain how to get a forward representation of time.
popsim-consortium/demes-spec pull request #159
Opened 2022-07-31 20:20 UTC by molpopgen

In response to one of the reviewers.

I wrote this "from memory", so it'd help to get a close look from @apragsdale, who wrote the first convert for fwdpy11.

2022-08-01 08:21 UTC, grahamgower requested changes
Thanks @molpopgen. I left a few suggestions.

2022-08-01 08:21 UTC, grahamgower commented on docs/specification.md
> +(sec_appendix_bacwards_to_forwards)=
```suggestion
(sec_appendix_backwards_to_forwards)=
```

2022-08-01 08:21 UTC, grahamgower commented on docs/specification.md
> +To convert times in a `demes` model into a forward-time representation:
I think this needs a small intro paragraph for context. And we must note that this should be done only on a fully-resolved and validated model. I.e. an MDM model.

```suggestion
Times in Demes models use a backwards-time convention, where the value `0` represents
now and time values increase towards the past.
However, many simulators use the opposite convention, where time `0` represents
some time in the past and time values increase towards the present.
To convert times in a Demes MDM model into a forward-time representation:
```

2022-08-01 08:21 UTC, grahamgower commented on docs/specification.md
> +  epoch time, etc..
The minimum epoch `end_time` value in the (resolved) graph. It shouldn't be necessary to check pulse or migration times, as these will always lie inside the existence time interval of some deme. This value will usually be 0.

2022-08-01 08:21 UTC, grahamgower commented on docs/specification.md
> +  in a graph.
Can we be more explicit here? I think it will be:
The most ancient non-infinite time out of: epoch `start_time`, epoch `end_time`, migration `start_time`, or pulse `time`.
I'm not sure if epoch `end_time` is really needed, but maybe there's an edge case here?

2022-08-01 08:21 UTC, grahamgower commented on docs/specification.md
> +* Given these definitions, `f = b + d - 1 - t`, where `t` is a backwards time in the `demes` model and `f` is the forwards-time equivalent.
```suggestion
* Given these definitions, `f = b + d - 1 - t`, where `t` is a backwards time in the Demes model and `f` is the forwards-time equivalent.
```

2022-08-01 15:46 UTC, molpopgen commented on docs/specification.md
> +  in a graph.
I don't think that the end_time is needed?  Where it would come up is a founder deme whose first epoch ends with a size change, and the second epoch is the most ancient start time.  For that case, we start with the second epoch and the downstream code has to "do the right thing" to know what the sizes are prior to that.

2022-08-01 15:53 UTC, grahamgower commented on docs/specification.md
> +  in a graph.
How about this? I would expect a forward-simulator to run the burn-in phase and then the simulation is complete.
```yaml
demes:
  - name: A
    epochs:
      - start_size: 100
        end_time: 100
```

2022-08-01 16:13 UTC, apragsdale commented on docs/specification.md
> +  migration `start_time`, or pulse `time.
"time" is missing a `

2022-08-01 16:13 UTC, apragsdale commented on docs/specification.md
> +  runs forward in time from `[0, d)`.
Do we want the half open intervals to be (0, d] instead (and then (0, b], and (b, b+d])? That would also remove the `-1` from `f = b + d - 1 - t`, which is more natural?

2022-08-01 16:22 UTC, molpopgen commented on docs/specification.md
> +  runs forward in time from `[0, d)`.
thoughts @grahamgower ?

2022-08-01 16:23 UTC, grahamgower commented on docs/specification.md
> +  runs forward in time from `[0, d)`.
Yeah, I think that's right. We currently have `(start_time, end_time]` and if we have a function `f(t)` that transforms a time `t`, then it would be nice if the new interval becomes `(f(start_time), f(end_time)]`.

Is this possible to dictate though? Maybe we end up not being able to specify this exactly because of how some simulators manage organism life cycles?

2022-08-01 17:24 UTC, molpopgen commented on docs/specification.md
> +  runs forward in time from `[0, d)`.
Life cycles can be handled one of two ways:

1. Fractional times, such that the integer portions reflect the parent/offspring deme sizes in the graph.
2. A linear transformation of the intervals described here.  For example, a simulation of a life cycle of 5 steps multiplies everything by 5 and commits to handling the book-keeping itself.

2022-08-01 18:32 UTC, apragsdale approved these changes

2022-08-02 06:13 UTC, grahamgower approved these changes
Perfect, thanks @molpopgen!

2022-09-02 09:26 UTC, merged

2022-09-02 09:27 UTC, grahamgower commented
Looks like we just forgot to merge this...