Remove nulls from schemas
popsim-consortium/demes-spec pull request #96
Opened 2021-06-30 13:01 UTC by jeromekelleher

Simplify the data models by removing unneeded nulls.

Related: #94, #93

2021-06-30 13:21 UTC, grahamgower requested changes
I think the reference implementation needs updating to set the description to the empty string when no description has been specified.

2021-06-30 13:23 UTC, grahamgower commented
Also, I think we'll want a separate test that runs `jsonschema.validate` on each of the valid test cases. Right now, the tests are just checking that the *resolved* output from the reference implementation can be validated against the schema.

2021-06-30 14:59 UTC, jeromekelleher commented
Thanks @grahamgower, good calls. I just need to update the resolved JSON now and it should all be good.

2021-07-01 07:41 UTC, grahamgower commented on test-cases/valid/toplevel_defaults_migration_02.yaml
> -- {rate: 0.3, demes: null, source: x, dest: y}
I think it would be better if these test cases were kept, but just moved into the "invalid" folder.

2021-07-01 11:17 UTC, jeromekelleher commented on test-cases/valid/toplevel_defaults_migration_02.yaml
> -- {rate: 0.3, demes: null, source: x, dest: y}
Right, good call. I'll move them.

2021-07-01 11:48 UTC, jeromekelleher commented
OK, should be ready to go now.

2021-07-01 11:53 UTC, grahamgower approved these changes
LGTM.

2021-07-01 11:55 UTC, merged